{{- if has "observability" .Values.feature }}
{{- if has "servicemesh" .Values.feature }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-federation
  labels:
    app.kubernetes.io/name: istio-prometheus
    component: service-monitor
spec:
  namespaceSelector:
    matchNames:
    - service-mesh
  selector:
    matchLabels:
      app: prometheus
  endpoints:
  - interval: 30s
    scrapeTimeout: 30s
    params:
      'match[]':
      - '{job=~"greetings"}'
    path: /federate
    targetPort: 9090
    honorLabels: true
    metricRelabelings:
    - sourceLabels: ["__name__"]
      regex: 'workload:(.*)'
      targetLabel: "__name__"
      action: replace
{{- else }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    component: service-monitor
  name: {{ include "app.fullname" . }}
spec:
  endpoints:
  - interval: 30s
    port: http-main
    scheme: http
    path: /q/metrics
  selector:
    matchLabels:
      {{- include "app.matchLabels" . | indent 6 }}
      component: {{ include "app.fullname" . }}-service
{{- end }}
{{- end }}