apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: {{ include "app.fullname" . }}-run-{{ .Release.Revision }}
  annotation:
    operator.tekton.dev/prune.resources: "taskrun, pipelinerun"
    operator.tekton.dev/prune.keep-since: 7200
  labels:
    tekton.dev/pipeline: build-maven
    app.kubernetes.io/name: {{ include "app.fullname" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  pipelineRef:
    name: {{ include "app.fullname" . }}
  serviceAccountName: {{ include "app.fullname" . }}-pipeline-bot
  timeout: 1h0m0s
  params:
    - name: appversion
      value: {{ .Chart.AppVersion }}
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: {{ include "app.fullname" . }}-maven
    - configMap:
        name: {{ include "app.fullname" . }}-maven-settings
      name: maven-settings