apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    {{- include "app.defaultLabels" . | indent 4 }}
  name: {{ include "app.fullname" . }}-route
spec:
  tls:
    termination: edge
  port:
    targetPort: http-main
  to:
    kind: Service
    name: {{ include "app.fullname" . }}-service